### ISSUE TITLE
Proovread error at the correcting step

### ISSUE THREAD

**Issue by Trevaly** [BioInf-Wuerzburg/proovread#80] opened 2016-09-15 01:22 UTC
Dear all,
I'm confronted to a new error that I don't manage to fixed nor to understand by my self.
Thanks in advance for your help and if I can do anything, let me know.

Jeremie

The code is a job array :
#!/bin/csh
#PBS -l mem=23000mb

#echo $PBS_ARRAY_INDEX >$HOME/script/test.$PBS_ARRAY_INDEX

source /usr/share/modules/init/csh
module load java

setenv PATH ${PATH}:/home12/caparmor/bioinfo/softs/sources/proovread/bin
setenv PATH ${PATH}:/home12/caparmor/bioinfo/softs/sources/proovread/util/SeqChunker/bin
setenv PERL5LIB /home12/caparmor/bioinfo/softs/perlmodules/lib/perl5/site_perl/5.10.0/:/home12/caparmor/bioinfo/softs/perlmodules:/home12/caparmor/bioinfo/softs/perlmodules/lib/perl5/5.10.0/x86_64-linux-thread-multi/
setenv PATH ${PATH}:/home12/caparmor/bioinfo/softs/sources/blast/ncbiblast+/2.2.29/bin/:/home12/caparmor/bioinfo/softs/sources/samtools/1.3.1/samtools/bin

setenv TMP /home/trash/Users/5_days_max/bioinfo
setenv TMPDIR /home/trash/Users/5_days_max/bioinfo

#going into result directory
cd /work/galaxy/p_margaritifera/genome/pacbio_manip/pacbio_corrected/

set read_dir=/work/galaxy/p_margaritifera/genome/illumina_40x_normalized
set data_dir=/work/galaxy/p_margaritifera/genome/pacbio_manip/40mb_chunk_fastq

proovread -l $data_dir/$PBS_ARRAY_INDEX.fastq -s $read_dir/PE_genome_40x_cat.fastq -p $PBS_ARRAY_INDEX --sr-qv-offset 33--sr-qv-offset 33 >>& /work/galaxy/p_margaritifera/genome/pacbio_manip/log_files/$PBS_ARRAY_INDEX.log

And here is the end of the log where the error is reported :

[Thu Sep 15 00:35:57 2016] Correcting Sequences (22 batches)
#------------------------------------------------------------------------------#
[Thu Sep 15 00:35:57 2016] Batch 1/22
perl -I/mnt/data/home12/bioinfo/softs/sources/proovread/bin/../lib/ /mnt/data/h\
ome12/bioinfo/softs/sources/proovread/bin/bam2cns --append 1 --bam 3/bwa-sr-1/3\
.bam --bin-size 20 --coverage 11.25 --ignore-weak-reads 0 --mask-weak-reads 0 -\
-max-ins-length 0 --max-ref-seqs 100 --prefix 3/bwa-sr-1/3.0 --qv-offset 33 --r\
ef 3/ccs-1/3.fq --ref-offset 0 
#------------------------------------------------------------------------------#
[Thu Sep 15 00:35:57 2016] Batch 2/22
perl -I/mnt/data/home12/bioinfo/softs/sources/proovread/bin/../lib/ /mnt/data/h\
ome12/bioinfo/softs/sources/proovread/bin/bam2cns --append 1 --bam 3/bwa-sr-1/3\
.bam --bin-size 20 --coverage 11.25 --ignore-weak-reads 0 --mask-weak-reads 0 -\
-max-ins-length 0 --max-ref-seqs 100 --prefix 3/bwa-sr-1/3.1 --qv-offset 33 --r\
ef 3/ccs-1/3.fq --ref-offset 1490345 
#------------------------------------------------------------------------------#
[Thu Sep 15 00:35:57 2016] Batch 3/22
perl -I/mnt/data/home12/bioinfo/softs/sources/proovread/bin/../lib/ /mnt/data/h\
ome12/bioinfo/softs/sources/proovread/bin/bam2cns --append 1 --bam 3/bwa-sr-1/3\
.bam --bin-size 20 --coverage 11.25 --ignore-weak-reads 0 --mask-weak-reads 0 -\
-max-ins-length 0 --max-ref-seqs 100 --prefix 3/bwa-sr-1/3.2 --qv-offset 33 --r\
ef 3/ccs-1/3.fq --ref-offset 3075595 
#------------------------------------------------------------------------------#
[Thu Sep 15 00:35:57 2016] Batch 4/22
perl -I/mnt/data/home12/bioinfo/softs/sources/proovread/bin/../lib/ /mnt/data/h\
ome12/bioinfo/softs/sources/proovread/bin/bam2cns --append 1 --bam 3/bwa-sr-1/3\
.bam --bin-size 20 --coverage 11.25 --ignore-weak-reads 0 --mask-weak-reads 0 -\
-max-ins-length 0 --max-ref-seqs 100 --prefix 3/bwa-sr-1/3.3 --qv-offset 33 --r\
ef 3/ccs-1/3.fq --ref-offset 4558286 
#------------------------------------------------------------------------------#
xargs: perl: terminated by signal 9
#------------------------------------------------------------------------------#
[Thu Sep 15 00:36:21 2016] bam2cns unexpectedly returned
	Exited at 'main'
	'/home12/caparmor/bioinfo/softs/sources/proovread/bin/proovread', line 1634
	Last call 'main::correct_sr_mt'
	'/home12/caparmor/bioinfo/softs/sources/proovread/bin/proovread', line 868

**Comment by thackl** [comment] 2016-09-15 02:37
Hi Jeremie,
Can you copy one of the batch commands and run them directly from the shell? That should give some more information about the problem.

**Comment by Trevaly** [comment] 2016-09-23 02:34
Hello,
first I apologize for delay between your response and mine. I work on a cluster and it's not always easy to shift from a PBS script to a direct running of the command  and  I needed help form the admin.

So our tests give several new informations : 
First I tried to run again the same job and look if the same bug always occurred at the same step with the same error log.

The response is yes it occurred at the same step (batch 4/22) but some times I have the following log instead of the first one

2nd log --------------------------------------------------------------------------------------------------------
[Fri Sep 16 22:03:56 2016] Batch 4/21
perl -I/mnt/data/home12/bioinfo/softs/sources/proovread/bin/../lib/ /mnt/data/h\
ome12/bioinfo/softs/sources/proovread/bin/bam2cns --append 1 --bam 14/bwa-sr-1/\
14.bam --bin-size 20 --coverage 11.25 --ignore-weak-reads 0 --mask-weak-reads 0\
 --max-ins-length 0 --max-ref-seqs 100 --prefix 14/bwa-sr-1/14.3 --qv-offset 33\
 --ref 14/ccs-1/14.fq --ref-offset 4916770
#------------------------------------------------------------------------------#
Out of memory!
#------------------------------------------------------------------------------#
[Fri Sep 16 22:04:19 2016] bam2cns unexpectedly returned
    Exited at 'main'
'/home12/caparmor/bioinfo/softs/sources/proovread/bin/proovread', line 1634
    Last call 'main::correct_sr_mt'
'/home12/caparmor/bioinfo/softs/sources/proovread/bin/proovread', line 868 
----------------------------------------------------------------------------------------------------------


What is surprising is that during our first test there was no memory problem (the size of the pacbio chunk is only 40Mo and there is 23Go of available memory to performed the job)

So we tried to run the command below directly,  on a chunk of 20Mo to see if it resolved the apparant memory problem and to do what you ask me, and it work well!
-------------------------------------------------------------------------------------------------------
perl -I/mnt/data/home12/bioinfo/softs/sources/proovread/bin/../lib/ /mnt/data/home12/bioinfo/softs/sources/proovread/bin/bam2cns --append 1 --bam 1/bwa-sr-1/1.bam --bin-size 20 --coverage 11.25 --ignore-weak-reads 0 --mask-weak-reads 0 --max-ins-length 0 --max-ref-seqs 100 --prefix 1/bwa-sr-1/1.3 --qv-offset 33 --ref 1/ccs-1/1.fq --ref-offset 5007751
----------------------------------------------------------------------------------------------------------

But when we try to run again the entire proovread job on the same 20Mo chunk with 23Go of available memory we obtained again the same error at the same step.

If you have an idea it will be great !!

Thanks again for your time,

Best regards,
Jeremie

**Comment by thackl** [comment] 2016-09-23 12:33
Hi Jeremie,

I am familiar with not always easy of computing on clusters :). The memory issue is weird. 23GB RAM should be  enough to run chunks as small as yours. How many chunks are you running in parallels (proovread --threads) and what version of Perl is running on the cluster (first line of proovread log)?

**Comment by Trevaly** [comment] 2016-09-26 18:13
Hi,
we are running 16 chunck in parrallel, and in total we have ~1100 chucks of 40Mo to correct.
The version of perl is 5.10.0

**Comment by thackl** [comment] 2016-09-26 18:40
OK, there's a potential explanation. Perl 5.10.**0** has some nasty memory leaks. I have seen  proovread fail on that version before. The leaks are Perl bugs, no real way around fixing them from my side. But here it get's weird. To prevent people from running into this problem, we made 5.10.**1** the minimum required version. Not sure, why that check failed on your system. Can you run
```perl -e 'use  5.010_001'```
and see what it says?

**Comment by Trevaly** [comment] 2016-09-26 18:48
I'have tryed your command line and apparently we don't have this version of perl

-------------------------------------------------------------------------------------------------
service7>55% perl -e 'use 5.010_001'
Perl v5.10.1 required--this is only v5.10.0, stopped at -e line 1.
BEGIN failed--compilation aborted at -e line 1.
service7>56% perl -e 'use 5.010_001'
Perl v5.10.1 required--this is only v5.10.0, stopped at -e line 1.
BEGIN failed--compilation aborted at -e line 1.
--------------------------------------------------------------------------------------------------------

I see with the admin of the cluster what we can do.

Thank for your responses again !
Jeremie

**Comment by thackl** [comment] 2016-09-26 18:52
That command is also integrated in proovread. It should have failed on your cluster nodes right away. Can you submit the command to the same cluster you tried to run proovread on. Maybe it has got a different perl version. Just put the line in a small .sh script and submit that to the queue.
```
#!/bin/bash
perl --version # just to see what version we are dealing with
perl -e 'use 5.010_001' # should fail on versions < 5.10.1
```

**Comment by Trevaly** [comment] 2016-09-26 19:37
This gave the same results, so I go back to proovread script and sawn that the cluster admin modify it... and change the line 
use  5.010_001;
by
use  v5.10

ARRRRRGGGGGGGGGG
I'm sorry for these, I didn't know that the original script was modifyed,  I 'm going to ask for the installation of the good version of perl and will tell you if it work.

Best regards
jeremie

**Comment by thackl** [comment] 2016-09-26 19:44
I feel you. Good luck with the admin. And if that does not work, let me know - I might be able to help you install your own, up-to-date Perl version locally. A bit more effort, but that should work in any case.

**Comment by thackl** [comment] 2016-09-26 19:47
Oh, and one more thing. Before you go up against your admin/reinstall Perl etc., it might be a good idea to make sure, it is a memory issue actually related to perl 5.10.0. One way would be that you (if possible) send me the first 12 chunks of data, and I run it here on a machine with a newer Perl version and monitor its memory consumption...

**Comment by Trevaly** [comment] 2016-09-26 21:10
yes I can do this and it will be super to do this test !
can you give me an email address where I can send you a link to download the data?
Mine is jeremie.vidal.dupiol@ifremer.fr

**Comment by thackl** [comment] 2016-10-04 22:39
OK, so seems like the problem is caused by the proovread version, since your data ran well on my machines. I am gonna close this issue for now, but feel free to reopen it if you encounter the problem again.

**Closed by thackl** 2016-10-04 22:39 UTC
